<a href="https://colab.research.google.com/github/esrakirbas/msc-thesis-reducing-hallucinations-in-medical-diagnosis/blob/main/code/python/reading_from_github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# file is on 'main' branch (public repo)
github_repo_url = "https://raw.githubusercontent.com/esrakirbas/medical-synthetic-prototype-data/main/data/"

# Read the CSV file into a pandas DataFrame
patients_url = (github_repo_url + "patients.csv")

conditions_url = (github_repo_url + "conditions.csv")

encounters_url = (github_repo_url + "encounters.csv")

observations_url = (github_repo_url + "observations.csv")

procedures_url = (github_repo_url + "procedures.csv")

allergies_url = (github_repo_url + "allergies.csv")

medications_url = (github_repo_url + "medications.csv")

## PATIENTS DATA
# Read the CSV file into a pandas DataFrame
patients_df = pd.read_csv(patients_url)

# Display the first few rows of the DataFrame
print("First 3 rows of patients data...>")
display(patients_df.head(3))

#CONDITIONS DATA
print("\nFirst 3 rows of conditions data...>")
conditions_df = pd.read_csv(conditions_url)
display(conditions_df.head(3))

#ENCOUNTERS DATA
print("\nFirst 3 rows of encounters data...>")
encounters_df = pd.read_csv(encounters_url)
display(encounters_df.head(3))

#OBSERVATIONS DATA
print("\nFirst 3 rows of observations data...>")
observations_df = pd.read_csv(observations_url)
display(observations_df.head(3))
print("\nTotal # of rows in observations data = " + str(len(observations_df)))

#PROCEDURES DATA
print("\nFirst 3 rows of procedures data...>")
procedures_df = pd.read_csv(procedures_url)
display(procedures_df.head(3))
print("\nTotal # of rows in procedures data = " + str(len(procedures_df)))

#ALLERGIES DATA
print("\nFirst 3 rows of allergies data...>")
allergies_df = pd.read_csv(allergies_url)
display(allergies_df.head(3))

#MEDICATIONS DATA
print("\nFirst 3 rows of medications data...>")
medications_df = pd.read_csv(medications_url)
display(medications_df.head(3))

First 3 rows of patients data...>

,Id,BIRTHDATE,DEATHDATE,FIRST,LAST,MARITAL,RACE,ETHNICITY,GENDER
0,a1733070-046a-4506-bba6-47f32652e9d7,1979-02-20,NaN,PATN001,PATS001,M,white,nonhispanic,M
1,f9ba83f7-9940-16ae-0854-24bd34bf1843,1971-11-23,NaN,PATN002,PATS002,D,white,nonhispanic,F
2,fc2d1fb9-862d-a60c-581a-519f5470d866,1975-09-16,NaN,PATN003,PATS003,M,white,nonhispanic,F

First 3 rows of conditions data...>

,START,STOP,PATIENT,ENCOUNTER,SYSTEM,CODE,DESCRIPTION
0,1997-04-22,NaN,a1733070-046a-4506-bba6-47f32652e9d7,a1733070-046a-4506-13b1-f518d757cdd0,http://snomed.info/sct,224299000,Received higher education (finding)
1,1997-04-22,NaN,a1733070-046a-4506-bba6-47f32652e9d7,a1733070-046a-4506-13b1-f518d757cdd0,http://snomed.info/sct,713458007,Lack of access to transportation (finding)
2,1989-01-10,NaN,f9ba83f7-9940-16ae-0854-24bd34bf1843,f9ba83f7-9940-16ae-158c-5cd0e5a140b9,http://snomed.info/sct,160968000,Risk activity involvement (finding)

First 3 rows of encounters data...>

,Id,START,STOP,PATIENT,ENCOUNTERCLASS,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION
0,f9ba83f7-9940-16ae-5f88-aea1af242f71,1973-02-01T07:34:23Z,1973-02-01T07:49:23Z,f9ba83f7-9940-16ae-0854-24bd34bf1843,ambulatory,185347001,Encounter for problem (procedure),256355007.0,Glycine max (substance)
1,a1733070-046a-4506-13b1-f518d757cdd0,1997-04-22T16:12:20Z,1997-04-22T16:59:47Z,a1733070-046a-4506-bba6-47f32652e9d7,wellness,162673000,General examination of patient (procedure),NaN,NaN
2,f9ba83f7-9940-16ae-81d1-8cdb486ca3ad,1973-02-16T21:34:23Z,1973-02-16T21:49:23Z,f9ba83f7-9940-16ae-0854-24bd34bf1843,ambulatory,185347001,Encounter for problem (procedure),609328004.0,Allergic disposition (finding)

First 3 rows of observations data...>

EmptyDataError: No columns to parse from file